### ISSUE TITLE
Destaque quando uma disciplina tem o foco

### ISSUE THREAD

**Issue by fanny** [Guardians-DSC/horarios-cc#68]
Uma coisa que acontece quando o usuario passa o mouse em cima de uma disciplina é o escurecimento do nível do cinza. Acho que isso ficaria mais destacado se uma cor distinta fosse escolhida, como por exemplo o próprio roxo de outras partes do site. O que acham?

**Comment by RaylaMedeiros** [comment]
Talvez um roxo num tom um pouco mais claro, pra dar destaque, mas não parecer selecionado

**Comment by MarceloWis** [comment]
Adicionei a cor `#8948bf ` para o hover com as disciplinas e a cor de fonte `#FFFFFF` para o hover ativo

**Comment by fanny** [comment]
Show!
